// Do not modify this file, it was automatically generated by CMake.

#ifndef COPILOT_CONFIG_H
#define COPILOT_CONFIG_H

// Plugins directory
#define COPILOT_CONFIG_DIR                 "@COPILOT_CONFIG_DIR@"

/// ngspice version string detected by pkg-config when available.
#define ASSISTANT_DLL_NAME      "@ASSISTANT_DLL_NAME@"

#endif  // COPILOT_CONFIG_H
