// Do not modify this file, it was automatically generated by CMake.

#ifndef COPILOT_CONFIG_H
#define COPILOT_CONFIG_H

#ifndef COPILOT_CONFIG_DIR
#define COPILOT_CONFIG_DIR                 "@COPILOT_CONFIG_DIR@"
#endif // COPILOT_CONFIG_DIR

#ifndef ASSISTANT_DLL_NAME
#define ASSISTANT_DLL_NAME      "@ASSISTANT_DLL_NAME@"
#endif // ASSISTANT_DLL_NAME

#endif  // COPILOT_CONFIG_H
